{
 "title": "CinéBrest",
 "time": { "from": "2025-02-20T11:56:51.356Z", "to": "2025-02-21T00:00:00.000Z" },
 "panels": [
  {
   "title": "Jours regardés",
   "type": "piechart",
   "description": "Le nombre de vue pour chaque jour",
   "gridPos": { "h": 20, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "views" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) FILTER (WHERE day = 0) AS \"Δ0\",\r\n    COUNT(*) FILTER (WHERE day = 1) AS \"Δ1\",\r\n    COUNT(*) FILTER (WHERE day = 2) AS \"Δ2\",\r\n    COUNT(*) FILTER (WHERE day = 3) AS \"Δ3\",\r\n    COUNT(*) FILTER (WHERE day = 4) AS \"Δ4\",\r\n    COUNT(*) FILTER (WHERE day = 5) AS \"Δ5\",\r\n    COUNT(*) FILTER (WHERE day = 6) AS \"Δ6\"\r\nFROM cinema_queries\r\nWHERE time BETWEEN TO_TIMESTAMP($__from/1000) AND TO_TIMESTAMP($__to/1000);\r\n"
    }
   ]
  },
  {
   "title": "Utilisateurs actifs",
   "type": "table",
   "description": "Liste des utilisateurs actifs (représentés par leurs IP) triée par nombre de visites",
   "gridPos": { "h": 20, "w": 5, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ip as \"IP\",\r\n  COUNT(*) as \"Visits\"\r\nFROM\r\n  cinema_queries\r\nWHERE\r\n  time BETWEEN TO_TIMESTAMP($__from/1000) AND TO_TIMESTAMP($__to/1000)\r\nGROUP BY\r\n  ip\r\nORDER BY\r\n  2 DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "OS",
   "type": "piechart",
   "description": "Camembert des OS les plus utilisés",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  os,\r\n  COUNT(*) as usage_count\r\nFROM\r\n  cinema_queries \r\nWHERE\r\n  time BETWEEN TO_TIMESTAMP($__from/1000) AND TO_TIMESTAMP($__to/1000)\r\nGROUP BY\r\n  os\r\nORDER BY\r\n  usage_count DESC"
    }
   ]
  },
  {
   "title": "Navigateurs",
   "type": "piechart",
   "description": "Camembert des navigateurs les plus utilisés",
   "gridPos": { "h": 10, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  browser,\r\n  COUNT(*) as usage_count\r\nFROM\r\n  cinema_queries \r\nWHERE\r\n  time BETWEEN TO_TIMESTAMP($__from/1000) AND TO_TIMESTAMP($__to/1000)\r\nGROUP BY\r\n  browser\r\nORDER BY\r\n  usage_count DESC\r\n"
    }
   ]
  },
  {
   "title": "Visites",
   "type": "timeseries",
   "description": "Visites au fil du temps, avec les IP uniques et visites",
   "gridPos": { "h": 10, "w": 10, "x": 13, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(time, 1d),\r\n  COUNT(DISTINCT ip) AS \"IP Uniques\"\r\nFROM\r\n  cinema_queries \r\nGROUP BY\r\n  1\r\nORDER BY\r\n  1 ASC;\r\n"
    },
    {
     "rawSql": "SELECT\r\n  DATE_TRUNC('day', time),\r\n  COUNT(*) AS \"Visites\"\r\nFROM\r\n  cinema_queries \r\nGROUP BY\r\n  1\r\nORDER BY\r\n  1 ASC;\r\n"
    }
   ]
  }
 ]
}